db_url: jdbc:mysql://calum.c2bryi0pfxhi.us-east-1.rds.amazonaws.com:3306/master_data
db_driver: com.mysql.jdbc.Driver
db_user: root
db_password: #edit me

output_file: companies.csv

batch_size: 50000

iterate_sql: select amee_company_id from tmp_profile_data_sep_20131029 order by amee_company_id asc

export_sql: |
  select
  amee_company_id,
  co_trad_name as "name",
  crn as national_identification_number,
  if(crn is null or crn = '', null, 12) as national_identification_system_code,
  if(uksic07 = 0, null, uksic07) as uk_sic_2007,
  location_indicator,
  -- if(ult_parent = 0, null, ult_parent) as gup_amee_company_id,
  weburl as company_website_url,
  phone as telephone,
  trad_ad1 as street_address_1,
  trad_ad2 as street_address_2,
  trad_ad3 as street_address_3,
  trad_ad4 as street_address_4,
  trad_postcode as postcode,
  trad_ad5 as city,
  trad_county as province_name,
  'GB' as country_code,
  date(bornyr) as established_at,
  ceo_title,
  ceo_name,
  reg_name as registered_name,
  if(substr(pad_desc, -1) = '.', pad_desc, null) as description,
  reg_ad1 as registered_street_address_1,
  reg_ad2 as registered_street_address_2,
  reg_ad3 as registered_street_address_3,
  reg_ad4 as registered_street_address_4,
  reg_postcode as registered_postcode,
  reg_town as registered_city,
  reg_county as registered_province_name,
  'GB' as registered_country_code,

  emissions as emissions_total,
  emissions_scope1,
  emissions_scope2,
  crc_emissions_tonnes_co2 as emissions_crc,
  emissions_source as emissions_status,
  water_withdrawn,
  water_discharged,
  water_source as water_status,
  waste_hazardous,
  waste_non_hazardous,
  waste_source as waste_status,
  if(emissions_source="modelled", date("2012-12-31"), date("2011-12-31")) as environmental_data_period_end,
  sustainability_url as sustainability_report_url,
  amee_score_group,
  -- if(score_d=0, null, score_d) as amee_industry_score,
  -- 1000000*(emissions/turnover) as financial_intensity,

  if(turnover='', null, turnover) as annual_sales_local,
  date(finex) as annual_sales_local_date,
  if(totass='', null, totass) as total_assets_local,
  date(finex) as total_assets_local_date,
  if(employment='', null, employment) as employees_total,
  date(finex) as employees_total_date,
  if(networth='', null, networth) as net_worth,
  date(finex) as net_worth_date,
  if(ptprof='', null, ptprof) as profit,
  date(finex) as profit_date,
  if(dormant='D','dormant',if(non_trading='r','non-trading','active')) as trading_status,
  case sal_type
    when 'A' then 'sourced'
    when 'M' then 'modelled'
    when 'B' then 'modelled'
    when 'U' then 'no_data'
    else 'no_data'
    end as sales_status,
  'GBP' as currency_code,
  financial_score

  from tmp_profile_data_sep_20131029 c
  where c.amee_company_id >= ?
  and c.amee_company_id <= ?


